export interface LoaneeCurentInformation {
    firstName: string,
    lastName: string,
    email: string,
    phoneNumber: string,
    nextOfKinRelationship: string,
    contactAddress: string,
    alternateEmail: string,
    alternatePhoneNumber: string,
    alternateContactAddress: string,
    stateOfResidence: string,
    levelOfEducation: string,
    others: string
}

export interface LoanDisbursal {
    "id": "143fc271-195e-4232-9a35-ce06513d8cb4",
    "firstName": "LOZOG",
    "lastName": "MOCK",
    "organizationName": "Ned Org Leave It alone please d",
    "cohortName": "Last",
    "programName": "Love men",
    "loaneeId": "04ea4203-28a8-44dd-af76-9c5d0f9e9eca",
    "cohortId": "5e7cbd87-1322-4c39-8987-589b0400e188",
    "amountRequested": null,
    "offerDate": "2025-10-23T14:42:16.997528",
    "startDate": "2020-10-16T00:00:00",
    "initialDeposit": 700000,
    "tuitionAmount": 3245545,
    "loanAmountOutstanding": 695992,
    "loanAmountRepaid": 0,
    "interestRate": 2.39,
    "repaymentRate": null,
    "debtPercentage": null,
    "interestIncurred": null,
    "cohortStartDate": "2020-10-16",
    "referredBy": "Ned Org Leave It alone please d",
    "status": null,
    "image": null,
    "loanTermsAndCondition": null,
    "creditScore": 0,
    "loanAmountRequested": 2545545,
    "loanAmountApproved": 695992,
    "createdDate": null,
    "dateTimeOffered": null,
    "userIdentity": {
        "id": null,
        "email": null,
        "firstName": "LOZOG",
        "lastName": "MOCK",
        "phoneNumber": null,
        "emailVerified": false,
        "enabled": false,
        "createdAt": null,
        "image": null,
        "gender": null,
        "dateOfBirth": null,
        "stateOfOrigin": null,
        "maritalStatus": null,
        "stateOfResidence": null,
        "levelOfEduction": null,
        "nationality": null,
        "residentialAddress": null,
        "role": null,
        "createdBy": null,
        "alternateEmail": null,
        "alternatePhoneNumber": null,
        "alternateContactAddress": null,
        "accessToken": null,
        "refreshToken": null,
        "organizationDomain": null,
        "deactivationReason": null,
        "reactivationReason": null,
        "additionalDetailsCompleted": false,
        "nextOfKinResponse": null,
        "mfaType": null,
        "mfaphoneNumber": null,
        "identityVerified": false
    },
    "nextOfKin": {
        "id": null,
        "firstName": null,
        "lastName": null,
        "email": null,
        "phoneNumber": null,
        "nextOfKinRelationship": null,
        "contactAddress": null
    },
    "loaneeLoanBreakDowns": null
}
export interface LoanProduct {
    "id": "c7a268c7-136d-4963-984a-46ff70ad869f",
    "name": "Growth Product",
    "moratorium": 4,
    "tenor": 12,
    "interestRate": 3,
    "termsAndCondition": "https://res.cloudinary.com/dfkxvsiiu/image/upload/v1756893540/loan-product-terms-and-conditions/API_delivery___documentation_jy56px.pdf",
    "createdAt": "2025-09-03",
    "totalAmountAvailable": 30000,
    "totalAmountDisbursed": 0,
    "obligorLoanLimit": 34,
    "totalOutstandingLoan": 0,
    "totalAmountRepaid": 0,
    "totalAmountEarned": 0,
    "loanProductSize": 30000,
    "costOfFund": "2.0",
    "mandate": "https://res.cloudinary.com/dfkxvsiiu/image/upload/v1756893528/loan-product-mandate/Student_Grade_sqxqj2.pdf",
    "sponsor": null,
    "bankPartner": "",
    "disbursementTerms": "",
    "investmentVehicleId": "8c2c1783-aaf4-4d4b-b53c-ce073f2fce8d",
    "investmentVehicleName": "A cure for wellness",
    "totalNumberOfLoanee": 0,
    "minRepaymentAmount": 3000,
    "vendors": null,
    "sponsors": null,
    "availableAmountToBeOffered": 0,
}

export interface LoanType {
    "loanProgressId": "b8b8c978-04c7-413e-b633-0d39d17e712b",
    "loanAmount": 580000,
    "amountOutstanding": 104902.59151956,
    "amountRepaid": 500000,
    "organizationName": "Walter",
    "loanType": "LOAN_DISBURSAL"
}
export interface AdminViewLoanType {
    "id": "",
    "firstName": "",
    loaneeId: '',
    cohortId: '',
    "lastName": "",
    "organizationName": "",
    "cohortName": "",
    "programName": "",
    "amountRequested": '',
    "offerDate": "",
    "startDate": "",
    "initialDeposit": number,
    "tuitionAmount": number,
    "loanAmountOutstanding": number,
    "loanAmountRepaid": number,
    "interestRate": number,
    "repaymentRate": string,
    "debtPercentage": string,
    "interestIncurred": string,
    "cohortStartDate": "",
    "referredBy": "",
    "status": string,
    "image": string,
    "creditScore": string,
    "loanAmountRequested": number,
    "loanAmountApproved": number,
    "createdDate": string,
    "dateTimeOffered": string,
    "userIdentity": {
        "id": null,
        "email": null,
        "firstName": "Dav",
        "lastName": "David",
        "phoneNumber": null,
        "emailVerified": false,
        "enabled": false,
        "createdAt": null,
        "image": null,
        "gender": null,
        "dateOfBirth": null,
        "stateOfOrigin": null,
        "maritalStatus": null,
        "stateOfResidence": null,
        "nationality": null,
        "residentialAddress": null,
        "role": null,
        "createdBy": null,
        "alternateEmail": null,
        "alternatePhoneNumber": null,
        "alternateContactAddress": null,
        "accessToken": null,
        "refreshToken": null,
        "organizationDomain": null,
        "deactivationReason": null,
        "reactivationReason": null,
        "additionalDetailsCompleted": false,
        "nextOfKinResponse": null,
        "identityVerified": false
    },
    "nextOfKin": {
        "id": null,
        "firstName": null,
        "lastName": null,
        "email": null,
        "phoneNumber": null,
        "nextOfKinRelationship": null,
        "contactAddress": null
    },
    "loaneeLoanBreakDowns": null
}
export interface LoaneetDetails {
    "id": string,
    "cohortId": string,
    "loanId": string,
    "createdBy": string,
    "creditScore": string,
    "createdAt": string,
    "updatedAt": string,
    "userIdentity": {
        "id": string,
        "email": string,
        "firstName": string,
        "lastName": string,
        "phoneNumber": string,
        "emailVerified": boolean,
        "enabled": boolean,
        "createdAt": string,
        "image": string,
        "gender": string,
        "dateOfBirth": string,
        "stateOfOrigin": string,
        "maritalStatus": string,
        "stateOfResidence": string,
        "nationality": string,
        "residentialAddress": string
        ,
        "role": string,
        "createdBy": string,
        "alternateEmail": string,
        "alternatePhoneNumber": string,
        "alternateContactAddress": string,
        "accessToken": string,
        "refreshToken": string,
        "organizationDomain": string,
        "deactivationReason": string,
        "reactivationReason": string,
        "nextOfKinResponse": string,
        "identityVerified": boolean
    },
    "loaneeLoanDetail": {
        "id": string,
        "tuitionAmount": string,
        "initialDeposit": string,
        "amountRequested": string,
        "amountReceived": string,
        "amountRepaid": string,
        "amountOutstanding": string,
        "loanBreakdown": string
    },
    "loaneeStatus": string,
    "highestLevelOfEducation": string,
    "nameOfPreviousInstitution": string,
    "programOfStudy": string,
    "institutionName": string,
    "programName": string,
    "cohortName": string,
    "cohortStartDate": string,
    "fitnessToWorkRating": string,
    "loanAmount": string,
    "interestRate": string,
    "paymentMoratoriumPeriod": string,
    "termsAndConditions": string,
    "tenor": string
}

export interface CohortInfo {
    id: string,
    name: string,
    numberOfLoanees: number,
    startDate: string,
    tuitionAmount: number,
    amountRequested: number,
    amountReceived: number,
    amountOutstanding: number
}

export interface LoaneeDetails {
    loanTermsAndCondition: string,
    repaymentPercentage: string,
    amountRepaid: string,
    amountOutstanding:string,
    amountReceived: string,
    "id": string,
    "firstName": string,
    "lastName": string,
    "organizationName": string,
    "cohortName": string,
    "programName": string,
    "amountRequested": string,
    "offerDate": string,
    "startDate": string,
    "initialDeposit": number,
    "tuitionAmount": number,
    "loanAmountOutstanding": number,
    "loanAmountRepaid": number,
    "interestRate": number,
    "repaymentRate": number,
    "debtPercentage": number,
    "interestIncurred": number,
    "cohortStartDate": string,
    "referredBy": string,
    "status": string,
    "image": string,
    "creditScore": number,
    "loanAmountRequested": number,
    "loanAmountApproved": number,
    "createdDate": string,
    "dateTimeOffered": string,
    "userIdentity": {
        "id": string,
        "email": string,
        "firstName": string,
        "lastName": string,
        "phoneNumber": string,
        "emailVerified": boolean,
        "enabled": boolean,
        "createdAt": string,
        "image": string,
        "gender": string,
        "dateOfBirth": string,
        "stateOfOrigin": string,
        "maritalStatus": string,
        "stateOfResidence": string,
        "nationality": string,
        "residentialAddress": string,
        "role": string,
        "createdBy": string,
        "alternateEmail": string,
        "alternatePhoneNumber": string,
        "alternateContactAddress": string,
        "accessToken": string,
        "refreshToken": string,
        "organizationDomain": string,
        "deactivationReason": string,
        "reactivationReason": string,
        "additionalDetailsCompleted": boolean,
        "nextOfKinResponse": null,
        "identityVerified": boolean
    },
    "nextOfKin": {
        "id": string,
        "firstName": string,
        "lastName": string,
        "email": string,
        "phoneNumber": string,
        "nextOfKinRelationship": string,
        "contactAddress": string
    },
    "loaneeLoanBreakDowns": [
        {
            "loaneeLoanBreakdownId": string,
            "itemName": string,
            "itemAmount": number,
            "currency": string
        },
        {
            "loaneeLoanBreakdownId": string,
            "itemName": string,
            "itemAmount": number,
            "currency": string
        },
        {
            "loaneeLoanBreakdownId": string,
            "itemName": string,
            "itemAmount": number,
            "currency": string
        }
    ]

}