export interface LoaneeCurentInformation {
    firstName: string,
    lastName: string,
    email: string,
    phoneNumber: string,
    nextOfKinRelationship: string,
    contactAddress: string,
    alternateEmail: string,
    alternatePhoneNumber: string,
    alternateContactAddress: string,
    stateOfResidence: string,
    levelOfEducation: string
}
export interface AdminViewLoanType {
    "id": "",
    "firstName": "",
    loaneeId: '',
    cohortId: '',
    "lastName": "",
    "organizationName": "",
    "cohortName": "",
    "programName": "",
    "amountRequested": '',
    "offerDate": "",
    "startDate": "",
    "initialDeposit": number,
    "tuitionAmount": number,
    "loanAmountOutstanding": number,
    "loanAmountRepaid": number,
    "interestRate": number,
    "repaymentRate": string,
    "debtPercentage": string,
    "interestIncurred": string,
    "cohortStartDate": "",
    "referredBy": "",
    "status": string,
    "image": string,
    "creditScore": string,
    "loanAmountRequested": number,
    "loanAmountApproved": number,
    "createdDate": string,
    "dateTimeOffered": string,
    "userIdentity": {
        "id": null,
        "email": null,
        "firstName": "Dav",
        "lastName": "David",
        "phoneNumber": null,
        "emailVerified": false,
        "enabled": false,
        "createdAt": null,
        "image": null,
        "gender": null,
        "dateOfBirth": null,
        "stateOfOrigin": null,
        "maritalStatus": null,
        "stateOfResidence": null,
        "nationality": null,
        "residentialAddress": null,
        "role": null,
        "createdBy": null,
        "alternateEmail": null,
        "alternatePhoneNumber": null,
        "alternateContactAddress": null,
        "accessToken": null,
        "refreshToken": null,
        "organizationDomain": null,
        "deactivationReason": null,
        "reactivationReason": null,
        "additionalDetailsCompleted": false,
        "nextOfKinResponse": null,
        "identityVerified": false
    },
    "nextOfKin": {
        "id": null,
        "firstName": null,
        "lastName": null,
        "email": null,
        "phoneNumber": null,
        "nextOfKinRelationship": null,
        "contactAddress": null
    },
    "loaneeLoanBreakDowns": null
}
export interface LoaneetDetails {
    "id": string,
    "cohortId": string,
    "loanId": string,
    "createdBy": string,
    "creditScore": string,
    "createdAt": string,
    "updatedAt": string,
    "userIdentity": {
        "id": string,
        "email": string,
        "firstName": string,
        "lastName": string,
        "phoneNumber": string,
        "emailVerified": boolean,
        "enabled": boolean,
        "createdAt": string,
        "image": string,
        "gender": string,
        "dateOfBirth": string,
        "stateOfOrigin": string,
        "maritalStatus": string,
        "stateOfResidence": string,
        "nationality": string,
        "residentialAddress": string
        ,
        "role": string,
        "createdBy": string,
        "alternateEmail": string,
        "alternatePhoneNumber": string,
        "alternateContactAddress": string,
        "accessToken": string,
        "refreshToken": string,
        "organizationDomain": string,
        "deactivationReason": string,
        "reactivationReason": string,
        "nextOfKinResponse": string,
        "identityVerified": boolean
    },
    "loaneeLoanDetail": {
        "id": string,
        "tuitionAmount": string,
        "initialDeposit": string,
        "amountRequested": string,
        "amountReceived": string,
        "amountRepaid": string,
        "amountOutstanding": string,
        "loanBreakdown": string
    },
    "loaneeStatus": string,
    "highestLevelOfEducation": string,
    "nameOfPreviousInstitution": string,
    "programOfStudy": string,
    "institutionName": string,
    "programName": string,
    "cohortName": string,
    "cohortStartDate": string,
    "fitnessToWorkRating": string,
    "loanAmount": string,
    "interestRate": string,
    "paymentMoratoriumPeriod": string,
    "termsAndConditions": string,
    "tenor": string
}

export interface CohortInfo {
    id: string,
    name: string,
    numberOfLoanees: number,
    startDate: string,
    tuitionAmount: number,
    amountRequested: number,
    amountReceived: number,
    amountOutstanding: number
}

export interface LoaneeDetails {
    "id": string,
    "firstName": string,
    "lastName": string,
    "organizationName": string,
    "cohortName": string,
    "programName": string,
    "amountRequested": string,
    "offerDate": string,
    "startDate": string,
    "initialDeposit": number,
    "tuitionAmount": number,
    "loanAmountOutstanding": number,
    "loanAmountRepaid": number,
    "interestRate": number,
    "repaymentRate": number,
    "debtPercentage": number,
    "interestIncurred": number,
    "cohortStartDate": string,
    "referredBy": string,
    "status": string,
    "image": string,
    "creditScore": number,
    "loanAmountRequested": number,
    "loanAmountApproved": number,
    "createdDate": string,
    "dateTimeOffered": string,
    "userIdentity": {
        "id": string,
        "email": string,
        "firstName": string,
        "lastName": string,
        "phoneNumber": string,
        "emailVerified": boolean,
        "enabled": boolean,
        "createdAt": string,
        "image": string,
        "gender": string,
        "dateOfBirth": string,
        "stateOfOrigin": string,
        "maritalStatus": string,
        "stateOfResidence": string,
        "nationality": string,
        "residentialAddress": string,
        "role": string,
        "createdBy": string,
        "alternateEmail": string,
        "alternatePhoneNumber": string,
        "alternateContactAddress": string,
        "accessToken": string,
        "refreshToken": string,
        "organizationDomain": string,
        "deactivationReason": string,
        "reactivationReason": string,
        "additionalDetailsCompleted": boolean,
        "nextOfKinResponse": null,
        "identityVerified": boolean
    },
    "nextOfKin": {
        "id": string,
        "firstName": string,
        "lastName": string,
        "email": string,
        "phoneNumber": string,
        "nextOfKinRelationship": string,
        "contactAddress": string
    },
    "loaneeLoanBreakDowns": [
        {
            "loaneeLoanBreakdownId": string,
            "itemName": string,
            "itemAmount": number,
            "currency": string
        },
        {
            "loaneeLoanBreakdownId": string,
            "itemName": string,
            "itemAmount": number,
            "currency": string
        },
        {
            "loaneeLoanBreakdownId": string,
            "itemName": string,
            "itemAmount": number,
            "currency": string
        }
    ]

}