export const ROLES = [
    "PORTFOLIO_MANAGER",
    "ORGANIZATION_ADMIN",
    "SPONSOR",
    "ORGANIZATION_ADMIN",
    "ADMIN",
    "DONOR",
    "ENDOWER",
    "INVESTOR",
    "LOANEE",
    "FINANCIER",
    "MEEDL_SUPER_ADMIN",
    "MEEDL_ASSOCIATE",
   " MEEDL_SUPER_ADMIN",
    "MEEDL_ADMIN",
    "ORGANIZATION_ASSOCIATE",
    "ORGANIZATION_SUPER_ADMIN",


]

