export const ROLES = [
    "PORTFOLIO_MANAGER",
    "ORGANIZATION_ADMIN",
    "SPONSOR",
    "ORGANIZATION_ADMIN",
    "ADMIN",
    "DONOR",
    "ENDOWER",
    "INVESTOR",
    "LOANEE",
    "FINANCIER",
    "MEEDL_SUPER_ADMIN",
    "PORTFOLIO_MANAGER_ASSOCIATE",
    "MEEDL_ADMIN",
    "ORGANIZATION_ASSOCIATE",
    "ORGANIZATION_SUPER_ADMIN",
    "COOPERATE_FINANCIER_SUPER_ADMIN",
    "COOPERATE_FINANCIER_ADMIN"

]

export const MEEDL_ADMINS_ROLES = [
    "MEEDL_SUPER_ADMIN",
    "PORTFOLIO_MANAGER_ASSOCIATE",
    "MEEDL_ADMIN",
    "PORTFOLIO_MANAGER",
    "COOPERATE_FINANCIER_ADMIN",
    "ORGANIZATION_ADMIN",

]
export const MEEDL_ROLES = [
    "ORGANIZATION_ADMIN",
    "SPONSOR",
    "ADMIN",
    "DONOR",
    "ENDOWER",
    "INVESTOR",
    "LOANEE",
    "FINANCIER",
    "ORGANIZATION_ASSOCIATE",
    "ORGANIZATION_SUPER_ADMIN",

]

export const FINANCIER_ADMINS_ROLES = [
    "COOPERATE_FINANCIER_SUPER_ADMIN",
    "COOPERATE_FINANCIER_ADMIN",
]



export const MEEDLE_ORG_ADMIN = [
    "PORTFOLIO_MANAGER",
    "ORGANIZATION_ADMIN",
    "ORGANIZATION_ADMIN",
    "MEEDL_SUPER_ADMIN",
    "PORTFOLIO_MANAGER_ASSOCIATE",
    "MEEDL_ADMIN",
    "ORGANIZATION_ASSOCIATE",
    "ORGANIZATION_SUPER_ADMIN",
]

