export const notificationMockData = [
    {
        id: "1mhg43",
        type: "Loan Application Received",
        subtitle: "Exciting Opportunity!",
        message: "We have successfully received your loan application. Our team is currently reviewing it and will get back to you shortly.",
        read: true,
        senderEmail: "support@loanprovider.com",
        senderName: "Loan Provider Team",
        receiverName: "John Doe", // Receiver's name added here
        timeSent: "Today 10:45 AM",
        callToActionRequired: false 
      },
      {
        id: "r45622",
        type: "Loan Approval",
        subtitle: "Good News!",
        message: "We are pleased to inform you that your loan application has been approved! You will receive the funds in your account within 24 hours.",
        read: true,
        senderEmail: "approvals@loanprovider.com",
        senderName: "Loan Approvals",
        receiverName: "Vanessa Oluchukwu", // Receiver's name added here
        timeSent: "1 day ago",
        callToActionRequired: false
      },
      {
        id: "yuth56575",
        type: "Loan Disbursement",
        subtitle: "Get Ready!",
        message: "Your loan amount has been disbursed to your account. Please check your bank account for the transaction details.",
        read: false,
        senderEmail: "disbursements@loanprovider.com",
        senderName: "Loan Disbursement ",
        receiverName: "Chris Johnson", // Receiver's name added here
        timeSent: "Today 9:30 AM",
        callToActionRequired: true // Call to action required to check bank account
      },
      {
        id: "465784",
        type: "Loan Repayment Reminder",
        subtitle: "Don't Miss Out!",
        message: "This is a friendly reminder that your loan repayment is due in 3 days. Please ensure sufficient funds are available in your account to avoid late fees.",
        read: false,
        senderEmail: "reminders@loanprovider.com",
        senderName: "Loan Repayment",
        receiverName: "Sarah Lee", // Receiver's name added here
        timeSent: "2 days ago",
        callToActionRequired: true // Call to action required to ensure funds
      },
      {
        id: "hjhjh3455",
        type: "Loan Statement",
        subtitle: "Monthly Statement",
        message: "Your monthly loan statement is now available. Please review your statement for details on your outstanding balance, interest, and repayment schedule.",
        read: true,
        senderEmail: "statements@loanprovider.com",
        senderName: "Loan Statements",
        receiverName: "Emily Davis", // Receiver's name added here
        timeSent: "Today 8:00 AM",
        callToActionRequired: true // Call to action required to review the statement
      },
      {
        id: "6hgnmt6rre4",
        type: "Loan Offer",
        subtitle: "You Have Mail!",
        message: "Dear customer, we have a special loan offer tailored just for you. Check your email for more details and take advantage of this limited-time offer.",
        read: false,
        senderEmail: "offers@loanprovider.com",
        senderName: "Loan Offers",
        receiverName: "Michael Brown", // Receiver's name added here
        timeSent: "3 days ago",
        callToActionRequired: true // Call to action required to check email and offer
      },
      {
        id: "111347",
        type: "Loan Application Update",
        subtitle: "Friendly Reminder",
        message: "Dear customer, we noticed that your loan application is incomplete. Please complete the required steps to expedite the approval process.",
        read: false,
        senderEmail: "support@loanprovider.com",
        senderName: "Loan Support Team",
        receiverName: "Olivia Carter", // Receiver's name added here
        timeSent: "Today 7:15 PM",
        callToActionRequired: true // Call to action required to complete application steps
      },
      {
        id: "dfe85566",
        type: "Loan Repayment Confirmation",
        subtitle: "Payment Received",
        message: "Dear customer, we have successfully received your loan repayment. Thank you for staying on track with your payments.",
        read: false,
        senderEmail: "payments@loanprovider.com",
        senderName: "Loan Payments Team",
        receiverName: "David Smith", // Receiver's name added here
        timeSent: "4 days ago",
        callToActionRequired: false // No action required
      },
      {
        id: "fbfggfhfn239",
        type: "Loan Interest Rate Update",
        subtitle: "Important Notice",
        message: "Dear customer, please be informed that there has been a change in your loan interest rate. Check your account for updated details.",
        read: false,
        senderEmail: "updates@loanprovider.com",
        senderName: "Loan Updates Team",
        receiverName: "Mia Wilson", // Receiver's name added here
        timeSent: "Today 6:00 PM",
        callToActionRequired: true // Call to action required to check account for updates
      },
      {
        id: "kmjhgy650",
        type: "Loan Pre-Approval",
        subtitle: "Congratulations!",
        message: "Dear customer, you have been pre-approved for a loan. Click here to view your pre-approved amount and terms.",
        read: false,
        senderEmail: "preapprovals@loanprovider.com",
        senderName: "Loan Pre-Approvals Team",
        receiverName: "Lucas Martinez", // Receiver's name added here
        timeSent: "5 days ago",
        callToActionRequired: true // Call to action required to view pre-approval details
      },
      {
        id: "11",
        type: "Loan Application Rejection",
        subtitle: "We Regret to Inform You",
        message: "Dear customer, after careful consideration, we regret to inform you that your loan application has been rejected. Please contact us for more details.",
        read: false,
        senderEmail: "rejections@loanprovider.com",
        senderName: "Loan Rejections Team",
        receiverName: "Sophia Taylor", 
        timeSent: "Today 5:45 PM",
        callToActionRequired: true 
      },
      {
        id: "1mhg43",
        type: "Loan Application Received",
        subtitle: "Exciting Opportunity!",
        message: "Dear valued customer, we have successfully received your loan application. Our team is currently reviewing it and will get back to you shortly.",
        read: true,
        senderEmail: "support@loanprovider.com",
        senderName: "Loan Provider Team",
        receiverName: "John Doe",
        timeSent: "Today 10:45 AM",
        callToActionRequired: false
      },
      {
        id: "r45622",
        type: "Loan Approval",
        subtitle: "Good News!",
        message: "Hello, Vanessa Oluchukwu. We are pleased to inform you that your loan application has been approved! You will receive the funds in your account within 24 hours.",
        read: true,
        senderEmail: "approvals@loanprovider.com",
        senderName: "Loan Approvals",
        receiverName: "Vanessa Oluchukwu",
        timeSent: "1 day ago",
        callToActionRequired: false
      },
      {
        id: "yuth56575",
        type: "Loan Disbursement",
        subtitle: "Get Ready!",
        message: "Dear customer, your loan amount has been disbursed to your account. Please check your bank account for the transaction details.",
        read: false,
        senderEmail: "disbursements@loanprovider.com",
        senderName: "Loan Disbursement",
        receiverName: "Chris Johnson",
        timeSent: "Today 9:30 AM",
        callToActionRequired: true
      },
      {
        id: "465784",
        type: "Loan Repayment Reminder",
        subtitle: "Don't Miss Out!",
        message: "This is a friendly reminder that your loan repayment is due in 3 days. Please ensure sufficient funds are available in your account to avoid late fees.",
        read: false,
        senderEmail: "reminders@loanprovider.com",
        senderName: "Loan Repayment",
        receiverName: "Sarah Lee",
        timeSent: "2 days ago",
        callToActionRequired: true
      },
      {
        id: "hjhjh3455",
        type: "Loan Statement",
        subtitle: "Monthly Statement",
        message: "Your monthly loan statement is now available. Please review your statement for details on your outstanding balance, interest, and repayment schedule.",
        read: true,
        senderEmail: "statements@loanprovider.com",
        senderName: "Loan Statements",
        receiverName: "Emily Davis",
        timeSent: "Today 8:00 AM",
        callToActionRequired: true
      },
      {
        id: "6hgrre47878",
        type: "Loan Offers",
        subtitle: "You Have Mail!",
        message: "Dear customer, we have a special loan offer tailored just for you. Check your email for more details and take advantage of this limited-time offer.",
        read: false,
        senderEmail: "offers@loanprovider.com",
        senderName: "Loan company",
        receiverName: "Michael Brown",
        timeSent: "3 days ago",
        callToActionRequired: true
      },
      {
        id: "111347",
        type: "Loan Application Update",
        subtitle: "Friendly Reminder",
        message: "Dear customer, we noticed that your loan application is incomplete. Please complete the required steps to expedite the approval process.",
        read: false,
        senderEmail: "support@loanprovider.com",
        senderName: "Loan Support Team",
        receiverName: "Olivia Carter",
        timeSent: "Today 7:15 PM",
        callToActionRequired: true
      },
      {
        id: "dfe85566",
        type: "Loan Repayment Confirmation",
        subtitle: "Payment Received",
        message: "Dear customer, we have successfully received your loan repayment. Thank you for staying on track with your payments.",
        read: false,
        senderEmail: "payments@loanprovider.com",
        senderName: "Loan Payments Team",
        receiverName: "David Smith",
        timeSent: "4 days ago",
        callToActionRequired: false
      },
      {
        id: "fbfggfhfn239",
        type: "Loan Interest Rate Update",
        subtitle: "Important Notice",
        message: "Dear customer, please be informed that there has been a change in your loan interest rate. Check your account for updated details.",
        read: false,
        senderEmail: "updates@loanprovider.com",
        senderName: "Loan Updates Team",
        receiverName: "Mia Wilson",
        timeSent: "Today 6:00 PM",
        callToActionRequired: true
      },
      {
        id: "kmjhgy650",
        type: "Loan Pre-Approval",
        subtitle: "Congratulations!",
        message: "Dear customer, you have been pre-approved for a loan. Click here to view your pre-approved amount and terms.",
        read: false,
        senderEmail: "preapprovals@loanprovider.com",
        senderName: "Loan Pre-Approvals Team",
        receiverName: "Lucas Martinez",
        timeSent: "5 days ago",
        callToActionRequired: true
      },
      {
        id: "11",
        type: "Loan Application Rejection",
        subtitle: "We Regret to Inform You",
        message: "Dear customer, after careful consideration, we regret to inform you that your loan application has been rejected. Please contact us for more details.",
        read: false,
        senderEmail: "rejections@loanprovider.com",
        senderName: "Loan Rejections Team",
        receiverName: "Sophia Taylor",
        timeSent: "Today 5:45 PM",
        callToActionRequired: true
      },
      {
        id: "12",
        type: "Loan Repayment Extension",
        subtitle: "Great News!",
        message: "Dear customer, we have approved your request for a loan repayment extension. Your new due date is now 30 days from today.",
        read: false,
        senderEmail: "extensions@loanprovider.com",
        senderName: "Loan Extensions",
        receiverName: "Ethan Walker",
        timeSent: "6 days ago",
        callToActionRequired: false
      },
      {
        id: "13",
        type: "Loan Account Update",
        subtitle: "Update Successful",
        message: "Dear customer, your loan account details have been successfully updated. Please review your account to ensure all information is correct.",
        read: false,
        senderEmail: "updates@loanprovider.com",
        senderName: "Updates Team",
        receiverName: "Isabella Moore",
        timeSent: "Today 4:30 PM",
        callToActionRequired: true
      },
      {
        id: "14",
        type: "Loan Security Alert",
        subtitle: "Alert!",
        message: "Dear customer, we detected unusual activity on your loan account. Please contact us immediately if you did not initiate this action.",
        read: false,
        senderEmail: "security@loanprovider.com",
        senderName: "Loan Security",
        receiverName: "Ava Lewis",
        timeSent: "7 days ago",
        callToActionRequired: true
      },
      {
        id: "15",
        type: "Loan Referral Program",
        subtitle: "New Connection",
        message: "Dear customer, refer a friend to our loan program and earn rewards! Click here to learn more about our referral program.",
        read: false,
        senderEmail: "referrals@loanprovider.com",
        senderName: "Augustine John",
        receiverName: "Noah Robinson",
        timeSent: "Today 3:15 PM",
        callToActionRequired: true
      },
      {
        id: "16",
        type: "Loan Feedback Request",
        subtitle: "We Value Your Opinion",
        message: "Dear customer, we would love to hear your feedback on your recent loan experience. Please take a moment to complete our survey.",
        read: false,
        senderEmail: "feedback@loanprovider.com",
        senderName: "Feedback Team",
        receiverName: "Mason Harris",
        timeSent: "8 days ago",
        callToActionRequired: true
      },
      {
        id: "17",
        type: "Loan Password Reset",
        subtitle: "Security Step",
        message: "Dear customer, you requested a password reset for your loan account. Click the link below to proceed with resetting your password.",
        read: false,
        senderEmail: "security@loanprovider.com",
        senderName: "Ted Ned",
        receiverName: "Lucas Scott",
        timeSent: "Today 2:00 PM",
        callToActionRequired: true
      },
      {
        id: "18",
        type: "Loan Feature Update",
        subtitle: "New Features Added",
        message: "Dear customer, we have added new features to your loan account to enhance your experience. Log in to explore the new features.",
        read: false,
        senderEmail: "updates@loanprovider.com",
        senderName: "Loan Updates",
        receiverName: "Charlotte Evans",
        timeSent: "9 days ago",
        callToActionRequired: true
      },
      {
        id: "19",
        type: "Loan Service Interruption",
        subtitle: "Service Notice",
        message: "Dear customer, our loan services are currently experiencing interruptions. We apologize for the inconvenience and are working to resolve the issue.",
        read: false,
        senderEmail: "support@loanprovider.com",
        senderName: "Ted Support",
        receiverName: "Amelia Wilson",
        timeSent: "Today 1:45 PM",
        callToActionRequired: false
      },
      {
        id: "20",
        type: "Loan Task Assigned",
        subtitle: "Task Assigned",
        message: "Dear customer, a new task has been assigned to your loan account. Please review and complete the task to proceed with your application.",
        read: true,
        senderEmail: "tasks@loanprovider.com",
        senderName: "Loan Tasks Team",
        receiverName: "James Taylor",
        timeSent: "10 days ago",
        callToActionRequired: true
      },
      {
        id: "21",
        type: "Loan Training Session",
        subtitle: "Upcoming Session",
        message: "Dear customer, join our upcoming training session on managing your loan account effectively. The session will be held on Monday at 9 AM.",
        read: false,
        senderEmail: "training@loanprovider.com",
        senderName: "Loan Training Team",
        receiverName: "Eleanor King",
        timeSent: "Today 12:30 PM",
        callToActionRequired: true
      },
      {
        id: "22",
        type: "Loan Billing Update",
        subtitle: "Billing Info",
        message: "Dear customer, your billing information has been updated successfully. Please review your account to ensure all details are correct.",
        read: false,
        senderEmail: "billing@loanprovider.com",
        senderName: "Loan Billing Team",
        receiverName: "Henry Wright",
        timeSent: "11 days ago",
        callToActionRequired: true
      },
      {
        id: "23",
        type: "Loan Event Invitation",
        subtitle: "You're Invited",
        message: "Dear customer, you are invited to our annual loan customer appreciation event. Join us for an evening of networking and fun!",
        read: false,
        senderEmail: "events@loanprovider.com",
        senderName: "Loan Events Team",
        receiverName: "Oliver Moore",
        timeSent: "Today 11:15 AM",
        callToActionRequired: true
      },
      {
        id: "25",
        type: "Loan Account Suspended",
        subtitle: "Action Required",
        message: "Dear customer, your loan account has been temporarily suspended due to suspicious activity. Please contact us immediately to resolve this matter.",
        read: false,
        senderEmail: "support@loanprovider.com",
        senderName: "Loan Support",
        receiverName: "Jackie Peters",
        timeSent: "Today 10:00 AM",
        callToActionRequired: true
      },
      {
        id: "26",
        type: "Loan Payment Update",
        subtitle: "Payment Update",
        message: "Dear customer, your loan payment schedule has been updated. Please review the new payment dates and amounts on your account.",
        read: false,
        senderEmail: "payments@loanprovider.com",
        senderName: "Loan Payment Team",
        receiverName: "Zoe Thompson",
        timeSent: "Yesterday 5:30 PM",
        callToActionRequired: true
      },
      {
        id: "27",
        type: "Loan Document Request",
        subtitle: "Document Required",
        message: "Dear customer, we require additional documents to process your loan application. Please upload the requested documents to your account.",
        read: false,
        senderEmail: "documents@loanprovider.com",
        senderName: "Loan Documents Team",
        receiverName: "Benjamin Clark",
        timeSent: "3 days ago",
        callToActionRequired: true
      },
      {
        id: "28",
        type: "Loan Prepayment Notice",
        subtitle: "Prepayment Opportunity",
        message: "Dear customer, you are eligible to make a prepayment on your loan without penalty. Consider paying early to reduce your interest charges.",
        read: false,
        senderEmail: "prepayments@loanprovider.com",
        senderName: "Loan Prepayment Team",
        receiverName: "Ella Green",
        timeSent: "5 days ago",
        callToActionRequired: true
      },
      {
        id: "29",
        type: "Loan Account Closure",
        subtitle: "Account Closed",
        message: "Dear customer, your loan account has been successfully closed. We appreciate your timely payments throughout the loan term. Thank you for your business!",
        read: false,
        senderEmail: "closure@loanprovider.com",
        senderName: "Loan Closure Team",
        receiverName: "Jack Brown",
        timeSent: "6 days ago",
        callToActionRequired: false
      },
      {
        id: "30",
        type: "Loan Payment Confirmation",
        subtitle: "Payment Confirmed",
        message: "Dear customer, your recent loan payment has been successfully processed. Thank you for your timely payment!",
        read: true,
        senderEmail: "payments@loanprovider.com",
        senderName: "Loan Payment Team",
        receiverName: "Sophia Taylor",
        timeSent: "Yesterday 1:30 PM",
        callToActionRequired: false
      }
  ];