export const programData = [{
    cohorts: 1,
    description: `Design thinking i s`,
    months: 24,
    title: `Program Title`,
    trainees: 11,
},
    {
        cohorts: 1,
        description: `Design thinking i s`,
        months: 24,
        title: `Program Title`,
        trainees: 11,
    },
    {
        cohorts: 1,
        description: `Design thinking i s`,
        months: 24,
        title: `Program Title`,
        trainees: 11,
    },
    {
        cohorts: 1,
        description: `Design thinking i s`,
        months: 24,
        title: `Program Title`,
        trainees: 11,
    },
    {
        cohorts: 1,
        description: `Design `,
        months: 24,
        title: `Program Title`,
        trainees: 11,
    },
    {
        cohorts: 1,
        description: `Design thinking i s`,
        months: 24,
        title: `Program Title`,
        trainees: 11,
    },
    {
        cohorts: 1,
        description: `Design thinking i s`,
        months: 24,
        title: `Program Title`,
        trainees: 11,
    },
    {
        cohorts: 1,
        description: `Design thinking i s`,
        months: 24,
        title: `Program Title`,
        trainees: 11,
    },
    {
        cohorts: 1,
        description: `Design thinking i s`,
        months: 24,
        title: `Program Title`,
        trainees: 11,
    },
    {
        cohorts: 1,
        description: `Design thinking i s`,
        months: 24,
        title: `Program Title`,
        trainees: 11,
    },
    {
        cohorts: 1,
        description: `Design thinking i s`,
        months: 24,
        title: `Program Title`,
        trainees: 11,
    },
    {
        cohorts: 1,
        description: `Design thinking i s`,
        months: 24,
        title: `Program Title`,
        trainees: 11,
    },
    {
        cohorts: 1,
        description: `Design thinking i s`,
        months: 24,
        title: `Program Title`,
        trainees: 11,
    }, {
        cohorts: 1,
        description: `Design thinking i s`,
        months: 24,
        title: `Program Title`,
        trainees: 11,
    },

]
