

export interface LoanType {

    "id": string,
    "firstName": string,
    "lastName": string,
    "organizationName": string,
    "cohortName": string,
    "programName": string,
    "amountRequested": string,
    "offerDate": string,
    "startDate": string,
    "initialDeposit": number,
    "tuitionAmount": number,
    "loanAmountOutstanding": number,
    "loanAmountRepaid": number,
    "interestRate": number,
    "repaymentRate": number,
    "debtPercentage": number,
    "interestIncurred": number,
    "cohortStartDate": string,
    "referredBy": string,
    "status": string,
    "image": string,
    "creditScore": string,
    "loanAmountRequested": string,
    "loanAmountApproved": string,
    "createdDate": string,
    "dateTimeOffered": string,
    "userIdentity": {
    "id": string,
        "email": string,
        "firstName": string,
        "lastName": string,
        "phoneNumber": string,
        "emailVerified": boolean,
        "enabled": boolean,
        "createdAt": string,
        "image": string,
        "gender": string,
        "dateOfBirth": string,
        "stateOfOrigin": string,
        "maritalStatus": string,
        "stateOfResidence": string,
        "nationality": string,
        "residentialAddress": string,
        "role": string,
        "createdBy": string,
        "alternateEmail": string,
        "alternatePhoneNumber": string,
        "alternateContactAddress": string,
        "accessToken": string,
        "refreshToken": string,
        "organizationDomain": string,
        "deactivationReason": string,
        "reactivationReason": string,
        "additionalDetailsCompleted": boolean,
        "nextOfKinResponse": string,
        "identityVerified": boolean
},
    "nextOfKin": {
    "id": string,
        "firstName": string,
        "lastName": string,
        "email": string,
        "phoneNumber": string,
        "nextOfKinRelationship": string,
        "contactAddress": string
},
    "loaneeLoanBreakDowns": string

}

export interface LoanProuctType {
    "id": "4c325043-cfe0-48a3-8eca-9335d445e24f",
    "name": "Junana",
    "moratorium": 2,
    "tenor": 6,
    "interestRate": 5,
    "termsAndCondition": "https://res.cloudinary.com/dfkxvsiiu/image/upload/v1759965450/loan-product-terms-and-conditions/CardinalStone_Balanced_Fund_Term_Sheet_tw7ufr.pdf",
    "createdAt": "2025-10-08",
    "totalAmountAvailable": 2000000,
    "availableAmountToBeDisbursed": 2000000,
    "availableAmountToBeOffered": 2000000,
    "totalAmountDisbursed": 0,
    "obligorLoanLimit": 1000000,
    "totalOutstandingLoan": 0,
    "totalAmountRepaid": 0,
    "totalAmountEarned": 0,
    "loanProductSize": 2000000,
    "costOfFund": "1.0",
    "mandate": "https://res.cloudinary.com/dfkxvsiiu/image/upload/v1759965442/loan-product-mandate/CardinalStone_Balanced_Fund_Term_Sheet_sdvekc.pdf",
    "sponsor": null,
    "bankPartner": "Access Bank",
    "disbursementTerms": "",
    "investmentVehicleId": "24935e0c-1b51-46a3-a366-b5a9788a5aca",
    "investmentVehicleName": "jumiaa",
    "totalNumberOfLoanee": 0,
    "minRepaymentAmount": 10000,
    "vendors": null,
    "sponsors": null
}


export interface LoanOrganization {

    "id": string,
    "name": string,
    "email": string,
    "websiteAddress": string,
    "invitedDate": string,
    "rcNumber": string,
    "tin": string,
    "phoneNumber": string,
    "numberOfPrograms": number,
    "status": string,
    "createdBy": string,
    "numberOfLoanees": number,
    "numberOfCohort": number,
    "loanRequestCount": number,
    "loanDisbursalCount": number,
    "loanOfferCount": number,
    "loanReferralCount": number,
    "totalDebtRepaid": number,
    "totalCurrentDebt": number,
    "totalHistoricalDebt": number,
    "repaymentRate": number,
    "serviceOfferings": string,
    "organizationEmployees": string,
    "logoImage": string,
    "bannerImage": string,
    "address": string

}

export interface CohortItems {
    "loanBreakdownId": string,
    "itemName": string,
    "itemAmount": string,
    "currency": string,
}
export interface loaneeLoanBreakDown {
    "loaneeLoanBreakdownId": string,
    "itemName": string,
    "itemAmount": string,
    "currency": string,
    "loanee": {
        "id": string,
        "cohortId": string,
        "createdAt": string,
        "updatedAt": string,
        "creditScoreUpdatedAt": string,
        "creditScore": string,
        "registryId": string,
        "userIdentity": {
            "id": string,
            "email": string,
            "firstName": string,
            "lastName": string,
            "phoneNumber": string,
            "emailVerified": boolean,
            "enabled": boolean,
            "createdAt": string,
            "image": string,
            "gender": string,
            "dateOfBirth": string,
            "stateOfOrigin": string,
            "maritalStatus": string,
            "stateOfResidence": string,
            "nationality": string,
            "residentialAddress": string,
            "role": string,
            "createdBy": string,
            "alternateEmail": string,
            "alternatePhoneNumber": string,
            "alternateContactAddress": string,
            "password": string,
            "accessToken": string,
            "refreshToken": string,
            "newPassword": string,
            "organizationDomain": string,
            "deactivationReason": string,
            "reactivationReason": string,
            "bvn": string,
            "nin": string,
            "identityVerified": boolean,


        }
    }
}
export interface LoanProductType {
    bankPartner: string,
    costOfFund: string,
    createdAt:string,
    disbursementTerms: string,
    id: string,
    interestRate: string,
    investmentVehicleId: string,
    investmentVehicleName: string,
    loanProductSize: string,
    mandate: string,
    minRepaymentAmount: string,
    moratorium: number,
    name: string,
    numberOfLoanees: number,
    obligorLoanLimit: number,
    sponsors: string[]
    tenor: number,
    termsAndCondition:string,
    totalAmountAvailable: number,
    totalAmountDisbursed:  number,
    totalAmountEarned:  number,
    totalAmountRepaid:  number,
}

export interface  ChangeOrganization {
    "id": string,
    "name": string,
    "email": string,
    "websiteAddress": string,
    "invitedDate": string,
    "rcNumber": string,
    "tin": string,
    "phoneNumber": string,
    "numberOfPrograms": number,
    "status": string,
    "createdBy": string,
    "numberOfLoanees": number,
    "numberOfCohort": number,
    "loanRequestCount": number,
    "loanDisbursalCount": number,
    "loanOfferCount": number,
    "loanReferralCount": number,
    "totalDebtRepaid": number,
    "totalCurrentDebt": number,
    "totalHistoricalDebt": number,
    "repaymentRate": number,
    "serviceOfferings": string,
    "organizationEmployees": string,
    "logoImage": string,
    "bannerImage": string,
    "address": string
}

export interface OverviewDetails {
    "portfolioName": string,
    "totalNumberOfInvestmentVehicle": number,
    "totalNumberOfCommercialFundsInvestmentVehicle": number,
    "totalNumberOfEndowmentFundsInvestmentVehicle": number,
    "totalNumberOfFinancier": number,
    "totalNumberOfIndividualFinancier": number,
    "totalNumberOfInstitutionalFinancier": number,
    "totalNumberOfLoans": number,
    "loanReferralPercentage": number,
    "loanRequestPercentage": number,
    "loanDisbursalPercentage": number,
    "loanOfferPercentage": number,
    "uploadLoanPercentage": number,
    "numberOfLoanees": number,
    "numberOfOrganizations": number,
    "numberOfLoanProducts": number,
    "historicalDebt": number,
    "disbursedLoanAmount": number,
    "netLoanPortfolio": number,
    "totalAmountEarned": number,
    "assetUnderManagement": string,
    "aumPercentage": number,
    "totalAvailable": string,
    "fundManagerFee": string,
    "trusteeFee": string,
    "percentageGain": number,
    "percentageLoss": number,
    "portfolioRiskLevel": string,
    "topPerformingInvestmentVehicles": string,
    "underPerformingInvestmentVehicles": string,
}