export interface CurrentMyInvestmentVehicleDetails {
    name: string,
    investmentVehicleType: string,
    fundManager : string,
    dateInvested: string,
    amountInvested: string,
    netAssetValue: string,
    netAssetValueInPercent: string,
    talentFunded: string,
    percentageOfPortfolio: string,
    startDate: string,
    maturityDate: string,
    incomeEarned: string,
    incomeInterval: string,
    designations: string,
    operationStatus: string,
    couponDistributionStatus: string,
    vehicleClosureStatus: string,
    investmentVehicleVisibility: string,
    mandate: string,
    interestRateOffered: string,
    fundRaisingStatus: string,
    deployingStatus: string
}